# Generated by Django 5.0.6 on 2024-05-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_account_licenseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_of_passport',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
