# Generated by Django 5.0.6 on 2024-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_licenseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='passport_image',
            field=models.ImageField(blank=True, upload_to='photos/accounts'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_passport',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='licenseid',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
