# Generated by Django 5.0.6 on 2024-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_passport_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_passport',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='licenseid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
