# Generated by Django 5.0.6 on 2024-05-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('date_of_passport', models.DateField()),
                ('licenseid', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(max_length=255)),
                ('vehicletype', models.CharField(max_length=255)),
                ('edangi', models.CharField(max_length=255)),
                ('trademark_or_manufacturer', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DriverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuccess', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.driver')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.trailer')),
            ],
        ),
        migrations.CreateModel(
            name='TrailerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='store/files')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.trailer')),
            ],
        ),
    ]
