# Generated by Django 5.0.6 on 2024-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='UR_truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crd', models.CharField(max_length=100)),
                ('ctype', models.CharField(max_length=100)),
                ('cedangi', models.CharField(max_length=100)),
                ('cmadename', models.CharField(max_length=100)),
                ('ccefno', models.CharField(max_length=100)),
                ('url2', models.CharField(max_length=200)),
                ('dpass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('dpass', models.CharField(max_length=100)),
                ('dletsence', models.CharField(max_length=100)),
                ('url1', models.CharField(max_length=200)),
            ],
        ),
    ]
