# Generated by Django 5.0.6 on 2024-05-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_ur_truck_userrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UR_truck',
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
