# Generated by Django 5.0.6 on 2024-05-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_user_request_userrequest_truck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Request',
        ),
        migrations.DeleteModel(
            name='UserRequest_Truck',
        ),
    ]
