# Generated by Django 5.0.6 on 2024-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_of_passport',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='account',
            name='licenseid',
            field=models.CharField(max_length=255, unique=True, default=''),
        ),
    ]
