# Generated by Django 5.0.6 on 2024-05-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_date_of_passport_account_licenseid'),
    ]

    operations = [
    ]
