# Generated by Django 5.0.6 on 2024-05-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_date_of_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_of_passport',
        ),
    ]
