# Generated by Django 5.0.6 on 2024-05-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_account_date_of_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='licenseid',
        ),
    ]
