# Generated by Django 5.0.6 on 2024-05-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_date_of_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='licenseid',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
