# Generated by Django 5.0.6 on 2024-05-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_date_of_passport_account_licenseid'),
        ('store_app', '0004_driver_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.RemoveField(
            model_name='driverimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverImage',
        ),
    ]
