# Generated by Django 5.0.6 on 2024-05-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_alter_application_driver_remove_driverimage_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date_of_passport', models.DateField()),
                ('licenseid', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.driver'),
        ),
        migrations.CreateModel(
            name='DriverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.driver')),
            ],
        ),
    ]
