# Generated by Django 5.0.6 on 2024-05-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_licenseid'),
        ('store_app', '0006_driver_alter_application_driver_driverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.DeleteModel(
            name='DriverImage',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
