# Generated by Django 5.0.6 on 2024-05-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_driver_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
